# SPDX-License-Identifier: Apache-2.0
"""SANA-WM realtime interactive session — S3 backend.

The streaming denoising stage runs the whole clip in one call. For LIVE control
(WASD/IJKL keyboard between chunks) we need an *incremental* engine: a session
that holds the per-block KV cache + decoder conv-cache + latent state and exposes
``step(camera_conditions, chunk_plucker) -> latent_chunk`` (optionally decoded),
generating ONE chunk per user action. This is the "Design B" incremental loop —
the engine the websocket route + WASD/IJKL web UI drive.

Reuses the validated streaming pieces: ``forward_long`` (chunk-causal DiT),
``SanaWMStreamingDenoisingStage._accumulate_kv_cache`` / ``_autoregressive_segments``
(KV accumulator + chunk grid), the fresh ``FlowMatchEulerDiscreteScheduler(shift=1.0)``,
and (when a causal VAE is attached) ``AutoencoderKLCausalLTX2Video.decode_chunk``.
"""

from __future__ import annotations

from typing import Optional

import torch

from sglang.multimodal_gen.runtime.models.dits.sana_wm import _NUM_STREAM_CACHE_SLOTS
from sglang.multimodal_gen.runtime.models.schedulers.scheduling_flow_match_euler_discrete import (
    FlowMatchEulerDiscreteScheduler,
)
from sglang.multimodal_gen.runtime.models.schedulers.scheduling_sana_wm_self_forcing import (
    SanaWMSelfForcingScheduler,
)
from . import parity_probe
from .streaming import (
    SanaWMStreamingDenoisingStage,
    self_forcing_denoise_chunk,
)


class SanaWMRealtimeSession:
    """Incremental, stateful streaming generator for interactive control.

    A new chunk is produced per ``step``; the recurrent GDN state / softmax
    concat-window / FFN tail (per-block KV cache) and the latent prefix carry
    across steps so a long video can be steered chunk-by-chunk in real time.
    """

    def __init__(
        self,
        transformer,
        *,
        denoising_step_list=(1000, 960, 889, 727, 0),
        num_frame_per_block: int = 3,
        num_cached_blocks: int = 2,
        sink_token: bool = True,
        cfg_scale: float = 1.0,
        device: Optional[torch.device] = None,
        dtype: torch.dtype = torch.bfloat16,
        vae=None,
    ) -> None:
        self.transformer = transformer
        self.vae = vae
        self.device = device or torch.device("cpu")
        self.dtype = dtype
        self.num_frame_per_block = int(num_frame_per_block)
        self.num_cached_blocks = int(num_cached_blocks)
        self.sink_token = bool(sink_token)
        self.cfg_scale = float(cfg_scale)
        self.use_cfg = self.cfg_scale > 1.0
        # Single-sourced sigma builder (same helper the batch stage uses;
        # validates the trailing-0 contract and divides by 1000).
        self._sigmas = SanaWMSelfForcingScheduler.build_per_chunk_sigmas(
            denoising_step_list
        )
        self._scheduler = FlowMatchEulerDiscreteScheduler(shift=1.0)
        self.num_blocks = len(transformer.blocks)
        self._reset_state()

    def _reset_state(self) -> None:
        self.latents: Optional[torch.Tensor] = None  # (B, C, T_so_far, h, w)
        self.first_latent: Optional[torch.Tensor] = None
        self.pos_embeds = None
        self.neg_embeds = None
        self.pos_mask = None
        self.neg_mask = None
        # kv_cache[chunk_idx][block][slot]; grown per step.
        self.kv_cache: list = []
        self.chunk_indices: list[int] = [0]
        self.chunk_idx = 0
        # Seeded noise: a full pre-noised latent buffer (B,C,T,h,w) sliced per
        # chunk (matches the offline LatentPreparation seeded draw), plus a
        # fallback seeded generator for chunks past the buffer's length.
        self._noise_buffer: Optional[torch.Tensor] = None
        self._noise_gen: Optional[torch.Generator] = None
        # Front-loaded autoregressive segmentation (matches the offline/official
        # _autoregressive_segments: chunk 0 carries the remainder). None => uniform
        # num_frame_per_block blocks (open-ended interactive streaming).
        self._segments: Optional[list[int]] = None

    @torch.no_grad()
    def reset(
        self,
        first_latent: torch.Tensor,
        pos_embeds: torch.Tensor,
        *,
        neg_embeds: Optional[torch.Tensor] = None,
        pos_mask: Optional[torch.Tensor] = None,
        neg_mask: Optional[torch.Tensor] = None,
        noise_buffer: Optional[torch.Tensor] = None,
        seed: Optional[int] = None,
        total_latent_frames: Optional[int] = None,
    ) -> None:
        """Start a new clip. ``first_latent`` is the VAE-encoded first frame
        ``(B, C, 1, h, w)`` (the condition); ``pos_embeds`` the Gemma-2 prompt
        embeds. Subsequent frames are generated by ``step``.

        ``noise_buffer`` (B, C, T, h, w) is a pre-noised seeded latent (frame 0
        is the condition slot, unused) sliced per chunk so the streaming output
        is reproducible and matches the offline seeded draw; ``seed`` seeds the
        fallback generator for chunks beyond the buffer (or when no buffer).

        ``total_latent_frames`` (the full clip's latent length, incl. the 1 cond
        frame) enables the official front-loaded segmentation: chunk 0 carries the
        ``total % num_frame_per_block`` remainder so the chunk boundaries / KV /
        camera windowing match the offline path. Omit for open-ended uniform
        streaming."""
        self._reset_state()
        if total_latent_frames is not None:
            self._segments = SanaWMStreamingDenoisingStage._autoregressive_segments(
                int(total_latent_frames), self.num_frame_per_block
            )
        self.first_latent = first_latent.to(self.device, self.dtype)
        self.latents = self.first_latent.clone()
        self.pos_embeds = pos_embeds.to(self.device, self.dtype)
        self.neg_embeds = None if neg_embeds is None else neg_embeds.to(self.device, self.dtype)
        self.pos_mask = pos_mask
        self.neg_mask = neg_mask
        self._noise_buffer = (
            None if noise_buffer is None
            else noise_buffer.to(self.device, self.dtype)
        )
        if seed is not None:
            self._noise_gen = torch.Generator(device=self.device).manual_seed(int(seed))

    def _chunk_noise(self, start_f: int, end_f: int, shape) -> torch.Tensor:
        """Noise for latent frames ``[start_f:end_f]``. Slices the seeded
        ``noise_buffer`` when it covers the range; otherwise draws from the
        seeded fallback generator (or global RNG if unseeded)."""
        if self._noise_buffer is not None and end_f <= self._noise_buffer.shape[2]:
            return self._noise_buffer[:, :, start_f:end_f].to(self.device, self.dtype)
        return torch.randn(
            *shape, device=self.device, dtype=self.dtype, generator=self._noise_gen
        )

    def _embeds_for_step(self):
        if self.use_cfg and self.neg_embeds is not None:
            embeds = torch.cat([self.neg_embeds, self.pos_embeds], dim=0)
            mask = (
                torch.cat([self.neg_mask, self.pos_mask], dim=0)
                if (self.pos_mask is not None and self.neg_mask is not None)
                else None
            )
        else:
            embeds, mask = self.pos_embeds, self.pos_mask
        return embeds, mask

    @torch.no_grad()
    def step(
        self,
        camera_conditions: Optional[torch.Tensor] = None,
        chunk_plucker: Optional[torch.Tensor] = None,
        *,
        n_frames: Optional[int] = None,
        decode: bool = False,
    ) -> torch.Tensor:
        """Generate the next chunk of ``n_frames`` latent frames.

        ``camera_conditions`` / ``chunk_plucker`` are this chunk's camera (e.g.
        from a WASD/IJKL action), sliced to the chunk's frames, on device. Returns
        the denoised latent chunk ``(B, C, n_frames, h, w)`` (or decoded pixels if
        ``decode`` and a causal VAE is attached). State advances in place.
        """
        if self.latents is None:
            raise RuntimeError("call reset() before step().")
        if self._segments is not None and self.chunk_idx + 1 < len(self._segments):
            # Front-loaded segmentation: chunk size = segment span, minus the 1
            # conditioning frame on chunk 0 (which first_latent already supplies).
            seg_len = self._segments[self.chunk_idx + 1] - self._segments[self.chunk_idx]
            n = seg_len - (self.first_latent.shape[2] if self.chunk_idx == 0 else 0)
        else:
            n = int(n_frames or self.num_frame_per_block)
        start_f = self.latents.shape[2] if self.chunk_idx > 0 else 0
        # Chunk 0 includes the conditioning first frame; later chunks are new.
        if self.chunk_idx == 0:
            chunk_frames = self.first_latent.shape[2] + n  # 1 (cond) + n
            end_f = chunk_frames
            cond_f = self.first_latent.shape[2]  # 1
            noise = self._chunk_noise(
                cond_f, cond_f + n,
                (self.first_latent.shape[0], self.first_latent.shape[1], n,
                 self.first_latent.shape[3], self.first_latent.shape[4]),
            )
            chunk_lat = torch.cat([self.first_latent, noise], dim=2)
        else:
            end_f = start_f + n
            chunk_frames = n
            chunk_lat = self._chunk_noise(
                start_f, end_f,
                (self.latents.shape[0], self.latents.shape[1], n,
                 self.latents.shape[3], self.latents.shape[4]),
            )

        B, C = chunk_lat.shape[0], chunk_lat.shape[1]
        self.chunk_indices.append(end_f)
        self.kv_cache.append([[None] * _NUM_STREAM_CACHE_SLOTS for _ in range(self.num_blocks)])
        chunk_kv, sink_num = SanaWMStreamingDenoisingStage._accumulate_kv_cache(
            self.kv_cache, self.chunk_idx, self.chunk_indices,
            self.num_cached_blocks, self.sink_token, self.num_blocks,
        )
        _dump_dir = parity_probe.probe_dir(parity_probe.ENV_RT_DUMP)
        if _dump_dir:  # parity harness: accumulated-KV checksums
            parity_probe.dump_obj(
                _dump_dir,
                f"kv_probe_{self.chunk_idx:03d}",
                parity_probe.kv_cache_checksums(chunk_kv, sink_num),
            )
        frame_index = (
            torch.arange(start_f, end_f, device=self.device, dtype=torch.long)
            if sink_num > 0 else None
        )

        # Condition mask: the first frame of chunk 0 is the (fixed) condition.
        cond_mask = torch.zeros(B, C, chunk_frames, *chunk_lat.shape[3:], device=self.device, dtype=torch.float32)
        cond_local = []
        if self.chunk_idx == 0:
            cond_mask[:, :, 0] = 1.0
            cond_local = [0]
        init_chunk = chunk_lat.clone()

        embeds, mask = self._embeds_for_step()
        prope = (camera_conditions, chunk_plucker)
        if _dump_dir:  # parity harness: per-chunk conditioning fed to forward_long
            parity_probe.dump_tensor(
                _dump_dir, f"cond_camera_{self.chunk_idx:03d}", camera_conditions
            )
            parity_probe.dump_tensor(
                _dump_dir, f"cond_plucker_{self.chunk_idx:03d}", chunk_plucker
            )
            if self.chunk_idx == 0:
                parity_probe.dump_tensor(_dump_dir, "cond_embeds", embeds)
                parity_probe.dump_tensor(_dump_dir, "cond_mask", mask)
                parity_probe.dump_obj(
                    _dump_dir,
                    "dit_fingerprint",
                    parity_probe.weights_fingerprint(self.transformer),
                )
        # Local-chunk closures for the SHARED per-chunk denoise implementation
        # (single source with the batch streaming stage; see
        # streaming.self_forcing_denoise_chunk).
        _local = {"lat": chunk_lat}

        def _get_chunk():
            return _local["lat"]

        def _set_chunk(denoised):
            lat = denoised.to(self.dtype)
            for loc in cond_local:
                lat[:, :, loc] = init_chunk[:, :, loc]
            _local["lat"] = lat

        def _on_noise_pred(ts_int, noise_pred):
            if _dump_dir and self.chunk_idx == 0:  # parity harness
                parity_probe.dump_tensor(
                    _dump_dir, f"noise_pred_c0_t{ts_int}", noise_pred
                )

        self.kv_cache[self.chunk_idx] = self_forcing_denoise_chunk(
            transformer=self.transformer,
            scheduler=self._scheduler,
            sigmas=self._sigmas,
            get_chunk=_get_chunk,
            set_chunk=_set_chunk,
            cond_mask=cond_mask,
            embeds=embeds,
            mask=mask,
            camera_conditions=camera_conditions,
            chunk_plucker=chunk_plucker,
            chunk_kv=chunk_kv,
            start_f=start_f,
            end_f=end_f,
            frame_index=frame_index,
            do_cfg=self.use_cfg,
            cfg_scale=self.cfg_scale,
            target_dtype=self.dtype,
            device=self.device,
            on_noise_pred=_on_noise_pred,
        )
        chunk_lat = _local["lat"]

        # Append to the running latent (chunk 0 already holds the first frame).
        if self.chunk_idx == 0:
            self.latents = chunk_lat
            new_frames = chunk_lat[:, :, 1:]
        else:
            self.latents = torch.cat([self.latents, chunk_lat], dim=2)
            new_frames = chunk_lat
        parity_probe.dump_tensor(  # parity harness: per-chunk stage-1 latent
            parity_probe.probe_dir(parity_probe.ENV_RT_DUMP),
            f"stage1_{self.chunk_idx:03d}_{start_f}_{end_f}",
            chunk_lat,
        )
        self.chunk_idx += 1

        if decode and self.vae is not None and hasattr(self.vae, "decode_chunk"):
            conv_cache = getattr(self, "_decoder_cache", None)
            if conv_cache is None:
                conv_cache = self.vae.reset_decoder_cache()
                self._decoder_cache = conv_cache
            return self.vae.decode_chunk(chunk_lat, conv_cache)
        return new_frames
